import "./globals.css";
import type { Metadata, NextPageContext } from "next";

import { cookies } from "next/headers";
import ReduxProvider from "@/redux/provider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayout = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayout) {
	const cookieStore = cookies();
	const theme = cookieStore.get("theme")?.value === "dark" ? false : true;

	return (
		<html
			suppressHydrationWarning
			lang="en"
			className={`${theme ? "" : "dark"}`}
		>
			<body>
				<div id="backdrop"></div>
				<div id="modal"></div>
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
