import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type HomeLayout = {
	children: React.ReactNode;
};

export default function HomeLayout({ children }: HomeLayout) {
	return (
		<>
			<Header />
			<main>{children}</main>
			<Footer />
		</>
	);
}
